INSERT INTO menu_orders(NAME, PRICE) VALUES('Refuel', 1500);
INSERT INTO menu_orders(NAME, PRICE) VALUES('Refuel Promax', 2700);
INSERT INTO menu_orders(NAME, PRICE) VALUES('Refuel Max', 2000);
INSERT INTO menu_orders(NAME, PRICE) VALUES('Wrapster', 1800);
INSERT INTO menu_orders(NAME, PRICE) VALUES('Turkey Salad', 1000);
INSERT INTO menu_orders(NAME, PRICE) VALUES('Chicken Salad', 800);
INSERT INTO menu_orders(NAME, PRICE) VALUES('Chocolate Ice-Cream', 550);
INSERT INTO menu_orders(NAME, PRICE) VALUES('Vanilla Ice-cream', 750);
INSERT INTO menu_orders(NAME, PRICE) VALUES('Hazel-nut fries', 1950);
INSERT INTO menu_orders(NAME, PRICE) VALUES('Fries and Chicken', 1750);
INSERT INTO menu_orders(NAME, PRICE) VALUES('Grilled Wings', 3500);
INSERT INTO menu_orders(NAME, PRICE) VALUES('Chips', 2900);
INSERT INTO menu_orders(NAME, PRICE) VALUES('Burger', 4500);
INSERT INTO menu_orders(NAME, PRICE) VALUES('Burrito', 7800);
INSERT INTO menu_orders(NAME, PRICE) VALUES('Mvp Box', 4850);
INSERT INTO menu_orders(NAME, PRICE) VALUES('Ad-star Box', 4400);
INSERT INTO menu_orders(NAME, PRICE) VALUES('Feast Bucket', 8650);
INSERT INTO menu_orders(NAME, PRICE) VALUES('Popcorn Chicken-large', 1700);
